<?php
/**
 * Created by PhpStorm.
 * User: Sandeep
 * Date: 05-Jan-2017
 * Time: 3:33 PM
 */

namespace Drupal\shm_mmr\Form;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class MmrSettings extends ConfigFormBase{
  function getFormId() {
    // TODO: Implement getFormId() method.
    return 'shm_mmr_admin_settings';
  }

  function getEditableConfigNames() {
    // TODO: Implement getEditableConfigNames() method.
    return [
      'shm_mmr.settings',
    ];
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = $this->config('shm_mmr.settings');

    $form['email_body'] = array(
      '#type' => 'text_format',
      '#title' => 'Email Body',
      '#format' => $config->get('email.body.format'),
      '#default_value' => $config->get('email.body.value'),
    );

    $form['pdf_cover'] = array(
      '#type' => 'text_format',
      '#title' => 'PDF Header',
      '#format' => $config->get('pdf.cover.format'),
      '#default_value' => $config->get('pdf.cover.value'),
    );

    $form['email_cc'] = array(
      '#type' => 'email',
      '#title' => 'Email Cc',
      '#default_value' => $config->get('email.cc'),
    );

    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    $config = \Drupal::service('config.factory')->getEditable('shm_mmr.settings');
    $config->set('email.body', $form_state->getValue('email_body'))->save();
    $config->set('pdf.cover', $form_state->getValue('pdf_cover'))->save();
    $config->set('email.cc', $form_state->getValue('email_cc'))->save();
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }



}