<?php
function ceir_registration_commerce_checkout_pane_info(){
  $checkout_panes = array();
  $checkout_panes['registration_completion_message'] = array(
    'title' => t('Registration completion message'),
    'page' => 'complete',
    'weight' => 10,
    'base' => 'registration_completion_pane',
  );
  return $checkout_panes;

}

function registration_completion_pane_settings_form($checkout_pane) {

  $form = array();
  $message = variable_get('registration_completion_message_field', commerce_checkout_completion_message_default());
  $form['container'] = array(
    '#type' => 'container',
    '#access' => filter_access(filter_format_load($message['format'])),
  );

  $form['container']['registration_completion_message_field'] = array(
  '#type' => 'text_format',
  '#title' => t('Registration completion message'),
  '#default_value' => $message['value'],
  );

  $var_info = array(
    'site' => array(
      'type' => 'site',
      'label' => t('Site information'),
      'description' => t('Site-wide settings and other global information.'),
    ),
    'commerce_order' => array(
      'label' => t('Order'),
      'type' => 'commerce_order',
    ),
  );

  $form['container']['registration_completion_message_field_help'] = RulesTokenEvaluator::help($var_info);
  return $form;
}

function registration_completion_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {

  $checkout_form= array();
  $message = variable_get('registration_completion_message_field', commerce_checkout_completion_message_default());
  $message['value'] = commerce_i18n_string('commerce:checkout:complete:message', $message['value'], array('sanitize' => FALSE));
  $message['value'] = token_replace($message['value'], array('commerce-order' => $order), array('clear' => TRUE));
  $message['value'] = check_markup($message['value'], $message['format']);
  $checkout_form['message'] = array(
    '#markup' => '<div class="checkout-completion-message">' . $message['value'] . '</div>',
  );
  return $checkout_form;
}